# Configuração de financiamento para o projeto JECH
# Remova ou comente as linhas que não se aplicam

# GitHub Sponsors
# github: [seuusuario]

# Patreon
# patreon: seuusuario

# Ko-fi
# ko_fi: seuusuario

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/seuusuario']

# Mensagem personalizada
# custom: ['https://seu-site.com/donate']
