#ifndef JECH_TOKENIZER_H
#define JECH_TOKENIZER_H

/**
 * Token types used in the lexical analysis phase
 */
typedef enum
{
	// Keywords
	TOKEN_SAY,
	TOKEN_KEEP,
	TOKEN_WHEN,

	// Symbols and literals
	TOKEN_LPAREN,
	TOKEN_RPAREN,
	TOKEN_STRING,
	TOKEN_SEMICOLON,
	TOKEN_NUMBER,
	TOKEN_BOOL,
	TOKEN_EQUAL,

	// Identifiers and misc
	TOKEN_IDENTIFIER,
	TOKEN_EOF,
	TOKEN_UNKNOWN
} JechTokenType;

/**
 * Token structure with type and value
 */
typedef struct
{
	JechTokenType type;
	char value[256];
} JechToken;

/**
 * List of tokens generated by the lexer
 */
typedef struct
{
	JechToken tokens[128];
	int count;
} JechTokenList;

/**
 * Lexical analysis function – converts source code to a token list
 */
JechTokenList _JechTokenizer_Lex(const char *source);

#endif
