// #ifndef LEXER_DEBUG_H
// #define LEXER_DEBUG_H

// #include "core/tokenizer.h"

// /**
//  * Prints all tokens generated by the lexer.
//  */
// void debug_print_tokens(const JechTokenList *list);

// #endif
