#ifndef LEXER_DEBUG_H
#define LEXER_DEBUG_H

#include "core/tokenizer.h"

/** 
 * Prints the tokens generated by the tokenizer in a human-readable format.
 * This function iterates through the token list and prints each token's type and value.
 *
 * @param list Pointer to the JechTokenList containing the tokens to be printed.
 */
void debug_print_tokens(const JechTokenList *list);

#endif
