#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include "core/vm.h"
#include "errors/error.h"

#define MAX_VARS 64

/**
 * Variable table for `keep` instruction
 */
typedef struct
{
	char name[MAX_STRING];
	char value[MAX_STRING];
} JechVariable;

static JechVariable variables[MAX_VARS];
static int var_count = 0;

/**
 * Sets or updates a variable in the runtime environment
 */
void _JechVM_SetVariable(const char *name, const char *value)
{
	for (int i = 0; i < var_count; i++)
	{
		if (strcmp(variables[i].name, name) == 0)
		{
			strncpy(variables[i].value, value, MAX_STRING);
			return;
		}
	}
	if (var_count < MAX_VARS)
	{
		strncpy(variables[var_count].name, name, MAX_STRING);
		strncpy(variables[var_count].value, value, MAX_STRING);
		var_count++;
	}
}

/**
 * Retrieves the value of a variable by name
 */
const char *_JechVM_GetVariable(const char *name)
{
	for (int i = 0; i < var_count; i++)
	{
		if (strcmp(variables[i].name, name) == 0)
		{
			return variables[i].value;
		}
	}
	return NULL;
}

/**
 * Debug function to print all variables in the VM
 */
void _debug_vm_dump_vars()
{
	extern JechVariable variables[];
	extern int var_count;

	for (int i = 0; i < var_count; i++)
	{
		printf("Variable: %s = %s\n", variables[i].name, variables[i].value);
	}
}

/**
 * Checks if a variable exists in the runtime environment
 */
bool variable_exists(const char *name)
{
	for (int i = 0; i < var_count; i++)
	{
		if (strcmp(variables[i].name, name) == 0)
		{
			return true;
		}
	}
	return false;
}

/**
 * Executes the bytecode generated by the compiler
 */
void _JechVM_Execute(const Bytecode *bc)
{
	for (int i = 0; i < bc->count; i++)
	{
		Instruction inst = bc->instructions[i];

		switch (inst.op)
		{
		case OP_SAY:
			if (inst.token_type == TOKEN_IDENTIFIER)
			{
				const char *value = _JechVM_GetVariable(inst.operand);
				if (value)
					printf("%s\n", value);
				else
					fprintf(stderr, "Runtime error: undefined variable '%s'\n", inst.operand);
			}
			else
			{
				printf("%s\n", inst.operand);
			}
			break;
		case OP_KEEP:
			if (_JechVM_GetVariable(inst.name) != NULL)
			{
				report_runtime_error("Variable already declared", inst.line, inst.column);
				exit(1);
			}
			_JechVM_SetVariable(inst.name, inst.operand);
			break;
		case OP_ASSIGN:
			if (variable_exists(inst.name))
			{
				_JechVM_SetVariable(inst.name, inst.operand);
			}
			else
			{
				report_runtime_error("Cannot assign to undeclared variable", 0, 0);
				exit(1);
			}
			break;
		case OP_BIN_OP:
		{
			const char *left_val = _JechVM_GetVariable(inst.operand);
			if (!left_val)
			{
				fprintf(stderr, "Runtime Error: Undefined variable '%s'\n", inst.operand);
				exit(1);
			}

			double left = atof(left_val);
			double right = atof(inst.operand_right);
			double result = 0;

			switch (inst.bin_op)
			{
			case TOKEN_PLUS:
				result = left + right;
				break;
			case TOKEN_MINUS:
				result = left - right;
				break;
			case TOKEN_STAR:
				result = left * right;
				break;
			case TOKEN_SLASH:
				if (right == 0)
				{
					fprintf(stderr, "Runtime Error: Division by zero\n");
					exit(1);
				}
				result = left / right;
				break;
			default:
				fprintf(stderr, "Runtime Error: Unsupported binary operator\n");
				exit(1);
			}

			char result_str[MAX_STRING];
			snprintf(result_str, sizeof(result_str), "%.2f", result);
			_JechVM_SetVariable(inst.name, result_str);
			break;
		}
		case OP_WHEN:
		{
			const char *var_val = _JechVM_GetVariable(inst.name);
			if (!var_val)
			{
				fprintf(stderr, "Runtime Error: Undefined variable '%s'\n", inst.name);
				exit(1);
			}

			double left = atof(var_val);
			double right = atof(inst.operand);
			bool is_true = false;

			switch (inst.bin_op)
			{
			case TOKEN_GT:
				is_true = (left > right);
				break;
			case TOKEN_LT:
				is_true = (left < right);
				break;
			case TOKEN_EQEQ:
				is_true = (left == right);
				break;
			default:
				fprintf(stderr, "Runtime Error: Unsupported operator in when.\n");
				exit(1);
			}

			if (is_true)
			{
				if (inst.token_type == TOKEN_IDENTIFIER)
				{
					const char *say_val = _JechVM_GetVariable(inst.operand_right);
					if (say_val)
						printf("%s\n", say_val);
					else
						fprintf(stderr, "Runtime Error: Undefined variable '%s'\n", inst.operand_right);
				}
				else
				{
					printf("%s\n", inst.operand_right);
				}
			}
			break;
		}
		case OP_END:
			return;
		default:
			fprintf(stderr, "VM error: unknown opcode %d\n", inst.op);
			return;
		}
	}
}
