#include <stdio.h>
#include <string.h>
#include "core/vm.h"

#define MAX_VARS 64

/**
 * Variable table for `keep` instruction
 */
typedef struct
{
	char name[MAX_STRING];
	char value[MAX_STRING];
} JechVariable;

static JechVariable variables[MAX_VARS];
static int var_count = 0;

/**
 * Sets or updates a variable in the runtime environment
 */
static void set_variable(const char *name, const char *value)
{
	for (int i = 0; i < var_count; i++)
	{
		if (strcmp(variables[i].name, name) == 0)
		{
			strncpy(variables[i].value, value, MAX_STRING);
			return;
		}
	}
	if (var_count < MAX_VARS)
	{
		strncpy(variables[var_count].name, name, MAX_STRING);
		strncpy(variables[var_count].value, value, MAX_STRING);
		var_count++;
	}
}

/**
 * Retrieves the value of a variable by name
 */
static const char *get_variable(const char *name)
{
	for (int i = 0; i < var_count; i++)
	{
		if (strcmp(variables[i].name, name) == 0)
		{
			return variables[i].value;
		}
	}
	return NULL;
}

/**
 * Executes the bytecode generated by the compiler
 */
void _JechVM_Execute(const Bytecode *bc)
{
	for (int i = 0; i < bc->count; i++)
	{
		Instruction inst = bc->instructions[i];

		switch (inst.op)
		{
		case OP_SAY:
			printf("%s\n", inst.operand);
			break;
		case OP_KEEP:
			set_variable(inst.name, inst.operand);
			break;
		case OP_END:
			return;
		default:
			fprintf(stderr, "VM error: unknown opcode %d\n", inst.op);
			return;
		}
	}
}
